In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import phylopandas as ph
%matplotlib inline

sns.set(style = 'white',context= 'notebook', rc = {'figure.figsize':(14,10)})

In [2]:
#NCBI enocding data
df = ph.read_fasta('sequences_cod2.fasta')
df

,id,sequence,description,label,uid
0,NC_045512.2:266..805,ATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAACACACGTCCAAC...,NC_045512.2:266..805 |leader protein [Severe a...,NC_045512.2:266..805,ZCho5JEsJ9
1,NC_045512.2:806..2719,GCATACACTCGCTATGTCGATAACAACTTCTGTGGCCCTGATGGCT...,NC_045512.2:806..2719 |nsp2 [Severe acute resp...,NC_045512.2:806..2719,K4dH2Hgb5b
2,NC_045512.2:2720..8554,GCACCAACAAAGGTTACTTTTGGTGATGACACTGTGATAGAAGTGC...,NC_045512.2:2720..8554 |nsp3 [Severe acute res...,NC_045512.2:2720..8554,FvXjzCMQ3F
3,NC_045512.2:8555..10054,AAAATTGTTAATAATTGGTTGAAGCAGTTAATTAAAGTTACACTTG...,NC_045512.2:8555..10054 |nsp4 [Severe acute re...,NC_045512.2:8555..10054,JTUcwXh8jD
4,NC_045512.2:10055..10972,AGTGGTTTTAGAAAAATGGCATTCCCATCTGGTAAAGTTGAGGGTT...,NC_045512.2:10055..10972 |3C-like proteinase [...,NC_045512.2:10055..10972,ynkrZgxA4M
...,...,...,...,...,...
103320,AY278554.2:27059..27250,ATGTTTCATCTTGTTGACTTCCAGGTTACAATAGCAGAGATATTGA...,AY278554.2:27059..27250 |unknown [SARS coronav...,AY278554.2:27059..27250,qa9DdftEUY
103321,AY278554.2:27258..27626,ATGAAAATTATTCTCTTCCTGACATTGATTGTATTTACATCTTGCG...,AY278554.2:27258..27626 |unknown [SARS coronav...,AY278554.2:27258..27626,CO0vmUJWH3
103322,AY278554.2:28115..28411,ATGGACCCCAATCAAACCAACGTAGTGCCCCCCGCATTACATTTGG...,AY278554.2:28115..28411 |unknown [SARS coronav...,AY278554.2:28115..28411,LIkR6Yh5g6
103323,AY278554.2:250..13398,ATGGAGAGCCTTGTTCTTGGTGTCAACGAGAAAACACACGTCCAAC...,AY278554.2:250..13398 |orf1a polyprotein [SARS...,AY278554.2:250..13398,EKJUdSXW5F
103324,AY269391.1:<1..>405,CAGAGCCATGCCTAACATGCTTAGGATAATGGCCTCTCTTGTTCTT...,"AY269391.1:<1..>405 |polymerase, partial [SARS...",AY269391.1:<1..>405,7fEhF6u7Q7

In [6]:
disp = df[(df['description'].str.find('join') != -1)]
disp.iloc[1,2]

'join(NC_045512.2:266..13468,NC_045512.2:13468..21555) |orf1ab polyprotein [Severe acute respiratory syndrome coronavirus 2]|YP_009724389.1|China'

In [7]:
df['description'].unique()

array(['NC_045512.2:266..805 |leader protein [Severe acute respiratory syndrome coronavirus 2]|YP_009742608.1|China',
       'NC_045512.2:806..2719 |nsp2 [Severe acute respiratory syndrome coronavirus 2]|YP_009742609.1|China',
       'NC_045512.2:2720..8554 |nsp3 [Severe acute respiratory syndrome coronavirus 2]|YP_009742610.1|China',
       ...,
       'AY278554.2:28115..28411 |unknown [SARS coronavirus CUHK-W1]|AAP13574.1|China',
       'AY278554.2:250..13398 |orf1a polyprotein [SARS coronavirus CUHK-W1]|AAP13575.1|China',
       'AY269391.1:<1..>405 |polymerase, partial [SARS coronavirus Vietnam]|AAP04003.1|Viet Nam'],
      dtype=object)

In [8]:
#Split description
x = df['description'].str.split("|", n=-1, expand = True)
#Protein names
y = x[1].str.split("[", n=-1, expand = True)
x

,0,1,2,3
0,NC_045512.2:266..805,leader protein [Severe acute respiratory syndr...,YP_009742608.1,China
1,NC_045512.2:806..2719,nsp2 [Severe acute respiratory syndrome corona...,YP_009742609.1,China
2,NC_045512.2:2720..8554,nsp3 [Severe acute respiratory syndrome corona...,YP_009742610.1,China
3,NC_045512.2:8555..10054,nsp4 [Severe acute respiratory syndrome corona...,YP_009742611.1,China
4,NC_045512.2:10055..10972,3C-like proteinase [Severe acute respiratory s...,YP_009742612.1,China
...,...,...,...,...
103320,AY278554.2:27059..27250,unknown [SARS coronavirus CUHK-W1],AAP13572.1,China
103321,AY278554.2:27258..27626,unknown [SARS coronavirus CUHK-W1],AAP13573.1,China
103322,AY278554.2:28115..28411,unknown [SARS coronavirus CUHK-W1],AAP13574.1,China
103323,AY278554.2:250..13398,orf1a polyprotein [SARS coronavirus CUHK-W1],AAP13575.1,China
103324,AY269391.1:<1..>405,"polymerase, partial [SARS coronavirus Vietnam]",AAP04003.1,Viet Nam

In [6]:
y

                           0                                                 1
0            leader protein   Severe acute respiratory syndrome coronavirus 2]
1                      nsp2   Severe acute respiratory syndrome coronavirus 2]
2                      nsp3   Severe acute respiratory syndrome coronavirus 2]
3                      nsp4   Severe acute respiratory syndrome coronavirus 2]
4        3C-like proteinase   Severe acute respiratory syndrome coronavirus 2]
...                      ...                                               ...
103320              unknown                          SARS coronavirus CUHK-W1]
103321              unknown                          SARS coronavirus CUHK-W1]
103322              unknown                          SARS coronavirus CUHK-W1]
103323    orf1a polyprotein                          SARS coronavirus CUHK-W1]
103324  polymerase, partial                          SARS coronavirus Vietnam]

[103325 rows x 2 columns]

In [9]:
final = pd.DataFrame(df['id'],y[0])

In [10]:
#DataFrame 
comparison = pd.DataFrame(df['id'])
comparison['type'] = y[0]
comparison['Loc'] = x[3]
comparison

                              id                  type       Loc
0           NC_045512.2:266..805       leader protein      China
1          NC_045512.2:806..2719                 nsp2      China
2         NC_045512.2:2720..8554                 nsp3      China
3        NC_045512.2:8555..10054                 nsp4      China
4       NC_045512.2:10055..10972   3C-like proteinase      China
...                          ...                   ...       ...
103320   AY278554.2:27059..27250              unknown      China
103321   AY278554.2:27258..27626              unknown      China
103322   AY278554.2:28115..28411              unknown      China
103323     AY278554.2:250..13398    orf1a polyprotein      China
103324       AY269391.1:<1..>405  polymerase, partial   Viet Nam

[103325 rows x 3 columns]

In [34]:
z =pd.DataFrame(comparison['id'].str.split(":",n=1, expand = True))

In [35]:
z = pd.merge(z,comparison,how ='inner',left_index=True,right_index=True)

In [42]:
z= z.drop('id',axis=1)
z

                  0             1                  type       Loc
0       NC_045512.2      266..805       leader protein      China
1       NC_045512.2     806..2719                 nsp2      China
2       NC_045512.2    2720..8554                 nsp3      China
3       NC_045512.2   8555..10054                 nsp4      China
4       NC_045512.2  10055..10972   3C-like proteinase      China
...             ...           ...                   ...       ...
103320   AY278554.2  27059..27250              unknown      China
103321   AY278554.2  27258..27626              unknown      China
103322   AY278554.2  28115..28411              unknown      China
103323   AY278554.2    250..13398    orf1a polyprotein      China
103324   AY269391.1      <1..>405  polymerase, partial   Viet Nam

[103325 rows x 4 columns]

In [37]:
z[0].unique()

array(['NC_045512.2', 'join(NC_045512.2', 'NC_004718.3', ...,
       'AY268049.1', 'join(AY278554.2', 'AY269391.1'], dtype=object)

In [43]:
trial = z[(z[0].str.find('join') != -1)]
trial

,0,1,type,Loc
22,join(NC_045512.2,"13442..13468,NC_045512.2:13468..16236)",RNA-dependent RNA polymerase,China
29,join(NC_045512.2,"266..13468,NC_045512.2:13468..21555)",orf1ab polyprotein,China
52,join(NC_004718.3,"13372..13398,NC_004718.3:13398..16166)",nsp12-pp1ab (RdRp),Canada
57,join(NC_004718.3,"265..13398,NC_004718.3:13398..21485)",orf1ab polyprotein (pp1ab),Canada
68,join(MT705205.1,"256..13458,MT705205.1:13458..21545)",ORF1ab polyprotein,Netherlands
...,...,...,...,...
103272,join(AY291451.1,"265..13398,AY291451.1:13398..21485)",putative polyprotein,Taiwan
103284,join(AY282752.2,"250..13383,AY282752.2:13383..21470)",putative polyprotein orf1ab,
103289,join(AY278488.2,"246..13379,AY278488.2:13379..21466)",orf1ab,
103303,join(AY278741.1,"265..13398,AY278741.1:13398..21485)",nonstructural polyprotein pp1ab,
103314,join(AY278554.2,"250..13383,AY278554.2:13383..21470)",putative orf1ab polyprotein,China

In [16]:
(trial[1].str.count(',')).unique()

array([1], dtype=int64)

In [44]:
trial2 =pd.DataFrame(trial[0].str.split("(",n=1, expand = True))

trial2

           0            1
22      join  NC_045512.2
29      join  NC_045512.2
52      join  NC_004718.3
57      join  NC_004718.3
68      join   MT705205.1
...      ...          ...
103272  join   AY291451.1
103284  join   AY282752.2
103289  join   AY278488.2
103303  join   AY278741.1
103314  join   AY278554.2

[8587 rows x 2 columns]

In [45]:
for i in range (0,8587):
    trial[0]= trial2[1]
trial = trial.reset_index()
trial

C:\Python\Python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,index,0,1,type,Loc
0,22,NC_045512.2,"13442..13468,NC_045512.2:13468..16236)",RNA-dependent RNA polymerase,China
1,29,NC_045512.2,"266..13468,NC_045512.2:13468..21555)",orf1ab polyprotein,China
2,52,NC_004718.3,"13372..13398,NC_004718.3:13398..16166)",nsp12-pp1ab (RdRp),Canada
3,57,NC_004718.3,"265..13398,NC_004718.3:13398..21485)",orf1ab polyprotein (pp1ab),Canada
4,68,MT705205.1,"256..13458,MT705205.1:13458..21545)",ORF1ab polyprotein,Netherlands
...,...,...,...,...,...
8582,103272,AY291451.1,"265..13398,AY291451.1:13398..21485)",putative polyprotein,Taiwan
8583,103284,AY282752.2,"250..13383,AY282752.2:13383..21470)",putative polyprotein orf1ab,
8584,103289,AY278488.2,"246..13379,AY278488.2:13379..21466)",orf1ab,
8585,103303,AY278741.1,"265..13398,AY278741.1:13398..21485)",nonstructural polyprotein pp1ab,
8586,103314,AY278554.2,"250..13383,AY278554.2:13383..21470)",putative orf1ab polyprotein,China

In [46]:
z

                  0             1                  type       Loc
0       NC_045512.2      266..805       leader protein      China
1       NC_045512.2     806..2719                 nsp2      China
2       NC_045512.2    2720..8554                 nsp3      China
3       NC_045512.2   8555..10054                 nsp4      China
4       NC_045512.2  10055..10972   3C-like proteinase      China
...             ...           ...                   ...       ...
103320   AY278554.2  27059..27250              unknown      China
103321   AY278554.2  27258..27626              unknown      China
103322   AY278554.2  28115..28411              unknown      China
103323   AY278554.2    250..13398    orf1a polyprotein      China
103324   AY269391.1      <1..>405  polymerase, partial   Viet Nam

[103325 rows x 4 columns]

In [47]:
for i in range (0,8587):
    z.iloc[(trial.iloc[i,0]),0] = trial.iloc[i,1]
z[0].unique()

array(['NC_045512.2', 'NC_004718.3', 'MT705205.1', ..., 'AY278554.2',
       'AY268049.1', 'AY269391.1'], dtype=object)

In [48]:
trial = trial.drop([1,'index'], axis=1)
trial

                0                              type          Loc
0     NC_045512.2     RNA-dependent RNA polymerase         China
1     NC_045512.2               orf1ab polyprotein         China
2     NC_004718.3               nsp12-pp1ab (RdRp)        Canada
3     NC_004718.3       orf1ab polyprotein (pp1ab)        Canada
4      MT705205.1               ORF1ab polyprotein   Netherlands
...           ...                               ...          ...
8582   AY291451.1             putative polyprotein        Taiwan
8583   AY282752.2      putative polyprotein orf1ab
8584   AY278488.2                           orf1ab
8585   AY278741.1  nonstructural polyprotein pp1ab
8586   AY278554.2      putative orf1ab polyprotein         China

[8587 rows x 3 columns]

In [49]:
z = z.drop(1, axis=1)

In [52]:
z = z.append(trial)
z = z.reset_index(drop=True)
z

                  0                              type     Loc
0       NC_045512.2                   leader protein    China
1       NC_045512.2                             nsp2    China
2       NC_045512.2                             nsp3    China
3       NC_045512.2                             nsp4    China
4       NC_045512.2               3C-like proteinase    China
...             ...                               ...     ...
120494   AY291451.1             putative polyprotein   Taiwan
120495   AY282752.2      putative polyprotein orf1ab
120496   AY278488.2                           orf1ab
120497   AY278741.1  nonstructural polyprotein pp1ab
120498   AY278554.2      putative orf1ab polyprotein    China

[120499 rows x 3 columns]

In [55]:
df2 = z.rename(columns={0:'id'})
df2

                 id                              type     Loc
0       NC_045512.2                   leader protein    China
1       NC_045512.2                             nsp2    China
2       NC_045512.2                             nsp3    China
3       NC_045512.2                             nsp4    China
4       NC_045512.2               3C-like proteinase    China
...             ...                               ...     ...
120494   AY291451.1             putative polyprotein   Taiwan
120495   AY282752.2      putative polyprotein orf1ab
120496   AY278488.2                           orf1ab
120497   AY278741.1  nonstructural polyprotein pp1ab
120498   AY278554.2      putative orf1ab polyprotein    China

[120499 rows x 3 columns]

In [91]:
#unique ids
len(df['id'].unique())

103259

In [92]:
row = pd.DataFrame(df['id'])
len(df['id'])

103325

In [19]:
col = pd.DataFrame(y[0].unique())
col

                        0
0         leader protein
1                   nsp2
2                   nsp3
3                   nsp4
4     3C-like proteinase
..                    ...
70  nucleocapsid protein
71    structural protein
72        matrix protein
73          ORF3 protein
74          ORF7 protein

[75 rows x 1 columns]

In [56]:
#Run by this for reset
g =df2.groupby(['id','type']).size()
g

id           type
AB257344.1   envelope protein                1
             membrane protein                1
             nucleocapsid protein            1
             polyprotein 1a                  1
             polyprotein 1ab                 3
                                            ..
NC_045512.2  nsp9                            2
             nucleocapsid phosphoprotein     1
             orf1a polyprotein               1
             orf1ab polyprotein              3
             surface glycoprotein            1
Length: 103043, dtype: int64

In [57]:
#Creating Final Frame
t0 =g.to_frame(name = 'size').reset_index()
#len(t0['type'].unique())
t0

                 id                          type  size
0        AB257344.1             envelope protein      1
1        AB257344.1             membrane protein      1
2        AB257344.1         nucleocapsid protein      1
3        AB257344.1               polyprotein 1a      1
4        AB257344.1              polyprotein 1ab      3
...             ...                           ...   ...
103038  NC_045512.2                         nsp9      2
103039  NC_045512.2  nucleocapsid phosphoprotein      1
103040  NC_045512.2            orf1a polyprotein      1
103041  NC_045512.2           orf1ab polyprotein      3
103042  NC_045512.2         surface glycoprotein      1

[103043 rows x 3 columns]

In [69]:
t0.tail(1000)

                 id                          type  size
102043   MT704061.1                        ORF7b      1
102044   MT704061.1                 ORF8 protein      1
102045   MT704061.1             envelope protein      1
102046   MT704061.1        membrane glycoprotein      1
102047   MT704061.1  nucleocapsid phosphoprotein      1
...             ...                           ...   ...
103038  NC_045512.2                         nsp9      2
103039  NC_045512.2  nucleocapsid phosphoprotein      1
103040  NC_045512.2            orf1a polyprotein      1
103041  NC_045512.2           orf1ab polyprotein      1
103042  NC_045512.2         surface glycoprotein      1

[1000 rows x 3 columns]

In [58]:
table =t0.pivot(index='id',columns='type',values='size')
table

type,2'-O-ribose methyltransferase,3'-to-5' exonuclease,3C-like proteinase,3a,3a protein,3b,3b protein,6,7a,7b,...,uncharacterized protein 6,uncharacterized protein 7a,uncharacterized protein 7b,uncharacterized protein 8a,uncharacterized protein 8b,uncharacterized protein 9b,uncharacterized protein 9c,unknown,unnamed protein product,"unnamed protein product, partial"
id,,,,,,,,,,,,,,,,,,,,,
AB257344.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
AB263618.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB889995.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB889996.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB889997.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MT704954.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT705205.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MT705206.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NC_004718.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NC_045512.2,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
table = table.replace(np.nan,0)
tmerger =table.reset_index()
tmerger

type,id,2'-O-ribose methyltransferase,3'-to-5' exonuclease,3C-like proteinase,3a,3a protein,3b,3b protein,6,7a,...,uncharacterized protein 6,uncharacterized protein 7a,uncharacterized protein 7b,uncharacterized protein 8a,uncharacterized protein 8b,uncharacterized protein 9b,uncharacterized protein 9c,unknown,unnamed protein product,"unnamed protein product, partial"
0,AB257344.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
1,AB263618.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AB889995.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AB889996.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AB889997.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,MT704954.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9374,MT705205.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9375,MT705206.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9376,NC_004718.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9377,NC_045512.2,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
t1 =df2.drop(['type'], axis=1)
t2 = t1.drop_duplicates(subset='id', keep='first')
t2

                 id          Loc
0       NC_045512.2        China
38      NC_004718.3       Canada
68       MT705205.1  Netherlands
80       MT705206.1  Netherlands
92       MT704812.1       Serbia
...             ...          ...
103289   AY278488.2
103300   AY278741.1
103312   AY278554.2        China
103313   AY268049.1
103324   AY269391.1     Viet Nam

[9378 rows x 2 columns]

In [61]:
#Final dataframe 
merged = pd.merge(tmerger,t2,on='id')
merged

,id,2'-O-ribose methyltransferase,3'-to-5' exonuclease,3C-like proteinase,3a,3a protein,3b,3b protein,6,7a,...,uncharacterized protein 7a,uncharacterized protein 7b,uncharacterized protein 8a,uncharacterized protein 8b,uncharacterized protein 9b,uncharacterized protein 9c,unknown,unnamed protein product,"unnamed protein product, partial",Loc
0,AB257344.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,
1,AB263618.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,
2,AB889995.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan
3,AB889996.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan
4,AB889997.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,MT704954.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangladesh
9374,MT705205.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Netherlands
9375,MT705206.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Netherlands
9376,NC_004718.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Canada
9377,NC_045512.2,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,China

In [62]:
#Encode Countries for color
from numpy import array
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
ie1= le1.fit_transform(array(merged['Loc']))
merged['Loc_enc']= pd.DataFrame(ie1)
merged['Loc_enc'] = merged['Loc_enc'].astype('int')
merged['Loc_enc'].unique()

array([ 0, 23,  7, 16, 54,  5, 45, 21, 50, 51, 25, 26, 34, 55, 46,  1, 17,
       11, 41, 27,  3, 29, 44,  4, 18, 31, 42, 32,  8, 33, 13, 20, 19, 48,
       12, 40, 49, 14, 39, 43,  9, 30, 36, 24, 53, 15, 52,  2, 35, 22, 37,
       10, 28, 47, 38,  6])

In [63]:
merged

,id,2'-O-ribose methyltransferase,3'-to-5' exonuclease,3C-like proteinase,3a,3a protein,3b,3b protein,6,7a,...,uncharacterized protein 7b,uncharacterized protein 8a,uncharacterized protein 8b,uncharacterized protein 9b,uncharacterized protein 9c,unknown,unnamed protein product,"unnamed protein product, partial",Loc,Loc_enc
0,AB257344.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,,0
1,AB263618.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0
2,AB889995.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan,23
3,AB889996.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan,23
4,AB889997.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,MT704954.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangladesh,2
9374,MT705205.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Netherlands,30
9375,MT705206.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Netherlands,30
9376,NC_004718.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Canada,5
9377,NC_045512.2,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,China,7

In [64]:
#Save pickle file for data
merged.to_pickle(r'C:\Users\hp\Desktop\IMP Stuff\AlgoAsylum\UMAP\feature_encoded_new.pkl')

In [2]:
#Use for future runs
merged = pd.read_pickle('feature_encoded_new.pkl')
merged

,id,2'-O-ribose methyltransferase,3'-to-5' exonuclease,3C-like proteinase,3a,3a protein,3b,3b protein,6,7a,...,uncharacterized protein 7b,uncharacterized protein 8a,uncharacterized protein 8b,uncharacterized protein 9b,uncharacterized protein 9c,unknown,unnamed protein product,"unnamed protein product, partial",Loc,Loc_enc
0,AB257344.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,,0
1,AB263618.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0
2,AB889995.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan,23
3,AB889996.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan,23
4,AB889997.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Japan,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9373,MT704954.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangladesh,2
9374,MT705205.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Netherlands,30
9375,MT705206.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Netherlands,30
9376,NC_004718.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Canada,5
9377,NC_045512.2,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,China,7

In [9]:
#Filtering countries for simplicity
fil = merged
ref =fil.groupby('Loc_enc').count() #reference
cond = fil.groupby('Loc_enc').count().iloc[fil['Loc_enc'],0] >=50 #Remove countries with less than 100 records
cond =cond.reset_index() #Normalise index
prc = fil[cond['id']]
cond2 = prc['Loc_enc']!=0 #Remove coutries with No country data
prc1 = prc[cond2]
cond2 = prc1['Loc_enc']!=50 #Remove USA
processed = prc1[cond2]
processed #UMAP Data

#fil.groupby('Loc').count().iloc[5,0]

,id,2'-O-ribose methyltransferase,3'-to-5' exonuclease,3C-like proteinase,3a,3a protein,3b,3b protein,6,7a,...,uncharacterized protein 7b,uncharacterized protein 8a,uncharacterized protein 8b,uncharacterized protein 9b,uncharacterized protein 9c,unknown,unnamed protein product,"unnamed protein product, partial",Loc,Loc_enc
8,AH012999.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,China,7
22,AY278554.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,China,7
25,AY286320.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,China,7
27,AY290752.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,China,7
47,AY365036.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,China,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9069,MT676390.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,India,17
9070,MT676397.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,India,17
9071,MT676411.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangladesh,2
9373,MT704954.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Bangladesh,2
9377,NC_045512.2,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,China,7

In [20]:
#UMAP Requirements
import umap.umap_ as umap
from sklearn.preprocessing import StandardScaler
reducer1 = umap.UMAP(n_neighbors=5, min_dist=0.8)
reducer2 = umap.UMAP(n_neighbors=15, min_dist=0.1)
reducer3 = umap.UMAP(n_neighbors=2, min_dist=0.9)
reducer4 = umap.UMAP(n_neighbors=15, min_dist=0.5)
prescale = processed.iloc[:,1:382].values #select only dimensional data
scaled= StandardScaler().fit_transform(prescale)
scaled.shape

(2811, 381)

In [13]:

embedding1 = reducer1.fit_transform(scaled)
embedding1.shape

C:\Python\Python37\lib\site-packages\sklearn\manifold\_spectral_embedding.py:236: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

(2811, 2)

In [24]:
embedding2 = reducer2.fit_transform(prescale)
embedding2.shape

(2811, 2)

In [21]:
embedding3 = reducer3.fit_transform(scaled)
embedding3.shape

C:\Python\Python37\lib\site-packages\sklearn\manifold\_spectral_embedding.py:236: UserWarning:

Graph is not fully connected, spectral embedding may not work as expected.

(2811, 2)

In [25]:
embedding = pd.DataFrame(embedding2)
processed = processed.reset_index(drop =True)
processed['X'] = 0
processed['Y'] = 0
for i in range(0,2811):
    processed.iloc[i,384] = embedding.iloc[i,0]
    processed.iloc[i,385] = embedding.iloc[i,1]
processed

,id,2'-O-ribose methyltransferase,3'-to-5' exonuclease,3C-like proteinase,3a,3a protein,3b,3b protein,6,7a,...,uncharacterized protein 8b,uncharacterized protein 9b,uncharacterized protein 9c,unknown,unnamed protein product,"unnamed protein product, partial",Loc,Loc_enc,X,Y
0,AH012999.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,China,7,10.580009,23.309380
1,AY278554.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,China,7,10.884387,23.000038
2,AY286320.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,China,7,23.607042,29.546753
3,AY290752.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,China,7,11.039478,23.098799
4,AY365036.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,China,7,10.983850,23.015509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2806,MT676390.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,India,17,11.839100,-0.649327
2807,MT676397.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,India,17,10.838466,-1.722883
2808,MT676411.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Bangladesh,2,10.298233,23.690157
2809,MT704954.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Bangladesh,2,-5.583660,-3.301453
2810,NC_045512.2,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,China,7,23.042620,29.648443

In [26]:
import plotly.express as px
import plotly
fig = px.scatter(processed, x='X',y ='Y', color= 'Loc')
plotly.offline.plot(fig)

'temp-plot.html'